test_suites:
  
  all:
    description: "Run all OLIDS data validation tests"
    categories:
      - referential_integrity
      - concept_mapping
      - person_patterns
      - all_null_columns
      - empty_tables
      - column_completeness
    
  referential_integrity:
    description: "Validate all foreign key relationships in OLIDS database"
    tests:
      - referential_integrity
      
  concept_mapping:
    description: "Validate concept mapping chains and terminology"
    tests:
      - concept_mapping
      
  person_patterns:
    description: "Validate person/patient data patterns and business rules"
    tests:
      - person_patterns
      
  all_null_columns:
    description: "Identify columns with 100% NULL values across all tables"
    tests:
      - all_null_columns
      
  empty_tables:
    description: "Identify tables with zero rows"
    tests:
      - empty_tables
      
  column_completeness:
    description: "Check completeness rates for critical columns"
    tests:
      - column_completeness

# Individual test configurations
test_config:
  
  # Data Quality Tests
  all_null_columns:
    description: "Identify columns with 100% NULL values across all tables"
    timeout: 300
    priority: high
    test_count: 710  # Based on actual test output showing 710 columns checked
    
  empty_tables:
    description: "Identify tables with zero rows"
    timeout: 180
    priority: high
    test_count: 28   # Based on actual test output showing 28 tables checked
    
  column_completeness:
    description: "Check completeness rates for critical columns"
    timeout: 300
    priority: high
    test_count: 6    # Based on actual test output showing 6 completeness checks
    
  # Referential Integrity Tests  
  referential_integrity:
    description: "Validates all 85 foreign key relationships in OLIDS database"
    timeout: 600
    priority: critical
    relationships_count: 85
    
  # Concept Mapping Tests
  concept_mapping:
    description: "Validates concept ID mappings through CONCEPT_MAP to CONCEPT chains"
    timeout: 240
    priority: critical
    concept_columns: 28
    
  # Business Rules Tests
  person_patterns:
    description: "Validates person/patient data patterns and business rules"
    timeout: 300
    priority: critical
    pattern_count: 13