test_suites:
  
  all:
    description: "Run all OLIDS data validation tests"
    categories:
      - referential_integrity
      - concept_mapping
      - business_rules
      - data_quality
    
  referential_integrity:
    description: "Test foreign key relationships between tables"
    tests:
      - patient_relationships
      - person_relationships
      - appointment_relationships
      
  concept_mapping:
    description: "Validate concept mapping chains and terminology"
    tests: []
      # Will be populated as tests are migrated:
      # - terminology_validation
      # - snomed_mapping
      # - concept_completeness
      
  business_rules:
    description: "Test business logic and data patterns"
    tests: []
      # Will be populated as tests are migrated:
      # - patient_validation
      # - person_validation
      # - clinical_validation
      
  data_quality:
    description: "Check data completeness and consistency"
    tests:
      - all_null_columns
      - column_completeness

# Individual test configurations
test_config:
  
  # Data Quality Tests
  all_null_columns:
    description: "Identify columns with 100% NULL values"
    timeout: 60
    priority: high
    
  column_completeness:
    description: "Check completeness rates for critical columns"
    timeout: 120
    priority: high
    
  temporal_validation:
    description: "Validate date/time ranges and lds_start_date_time"
    timeout: 90
    priority: medium
    
  episode_analysis:
    description: "Analyze patient registration coverage and missing episodes"
    timeout: 120
    priority: high
    
  # Referential Integrity Tests  
  patient_relationships:
    description: "Validate patient foreign key relationships"
    timeout: 180
    priority: critical
    relationships_count: 5
    
  person_relationships:
    description: "Validate person foreign key relationships"
    timeout: 150
    priority: critical
    relationships_count: 4
    
  appointment_relationships:
    description: "Validate appointment foreign key relationships"
    timeout: 120
    priority: high
    relationships_count: 3
    
  clinical_relationships:
    description: "Validate clinical data foreign keys"
    timeout: 300
    priority: critical
    relationships_count: 45
    
  # Concept Mapping Tests
  terminology_validation:
    description: "Test CONCEPT_MAP -> CONCEPT chains"
    timeout: 240
    priority: critical
    concept_columns: 28
    
  snomed_mapping:
    description: "Analyze SNOMED Description -> Concept mapping rates"
    timeout: 180
    priority: high
    
  # Business Rules Tests
  patient_validation:
    description: "Patient data integrity (NHS numbers, dates, addresses)"
    timeout: 150
    priority: critical
    test_count: 21
    
  person_validation:
    description: "Person records and patient-person relationships"
    timeout: 120
    priority: critical
    test_count: 20