# Environment Configuration Template for OLIDS UAT Testing Framework
# Copy this file to create your environment-specific configuration
# Example: copy to dev/uat/prod and adjust values.

name: "dev"  # One of: dev, uat, prod
description: "Development environment"

# Database configuration
databases:
  source: "YOUR_SOURCE_DB"         # Main OLIDS database
  terminology: "YOUR_TERMINOLOGY_DB"  # Terminology database (often same as source)
  results: "YOUR_RESULTS_DB"        # Results database for test outputs
  dictionary: "YOUR_DICTIONARY_DB"  # Data dictionary database

# Output configuration for CLI/UI
output:
  default_format: "table"           # table | json
  export_formats: ["json", "csv"]  # Allowed export formats
  max_display_rows: 100              # Maximum rows to display in terminal

# Schema configuration
schemas:
  masked: "YOUR_MASKED_SCHEMA"           # Main data schema
  terminology: "YOUR_TERMINOLOGY_SCHEMA" # Terminology schema
  tests: "YOUR_TESTS_SCHEMA"             # Test results schema

# Snowflake connection details
# Prefer using a Snow CLI connection; optional fields can override if needed
connection:
  snow_cli_connection: "your-connection-name"  # Snow CLI connection name (leave empty to use default)
  # Optional overrides (only needed if different from Snow CLI connection):
  # account: "your-snowflake-account"         # e.g., "abc12345.eu-west-1"
  # role: "YOUR_ROLE"                         # e.g., "OLIDS_USER_ROLE"
  # warehouse: "YOUR_WAREHOUSE"               # e.g., "OLIDS_WAREHOUSE"
  # host: "your-account.snowflakecomputing.com"  # For display purposes only

# Execution settings
execution:
  parallel_workers: 4        # Number of parallel test workers
  timeout_seconds: 300       # Test timeout in seconds
  retry_attempts: 3          # Number of retry attempts for failed connections

# Optional: Override default test configurations
# test_overrides:
#   column_completeness:
#     timeout: 600
#     parallel: false
#   referential_integrity:
#     timeout: 900

# Instructions:
# 1. Copy this file: cp config/environments/template.yml config/environments/your-env.yml
# 2. Replace placeholders with your actual values:
#    - name: dev | uat | prod
#    - YOUR_* placeholders for databases and schemas
#    - your-connection-name for your Snow CLI connection
# 3. Ensure your Snow CLI is configured with matching credentials
# 4. Validate setup: olids-test validate
